spring:
  application:
    name: iam-admin-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: ${APP_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ums}
    username: ${APP_DATASOURCE_USERNAME:postgres}
    password: ${APP_DATASOURCE_PASSWORD:imran1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${APP_JPA_DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:${KEYCLOAK_SERVER_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:bank-asia}}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:${KEYCLOAK_SERVER_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:bank-asia}/protocol/openid-connect/certs}

server:
  port: 8081
  servlet:
    context-path: /iam-admin-service
  error:
    include-message: never

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

app:
  security:
    role-source-clients:
      - ${KEYCLOAK_UMS_UI_CLIENT_ID:ums-ui}
      - ${KEYCLOAK_LMS_UI_CLIENT_ID:lms-ui}
  keycloak:
    auth:
      server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
      realm: ${KEYCLOAK_REALM:bank-asia}
      clients:
        ums-ui:
          client-id: ${KEYCLOAK_UMS_UI_CLIENT_ID:ums-admin-app}
        lms-ui:
          client-id: ${KEYCLOAK_LMS_UI_CLIENT_ID:lms-app}
    admin:
      server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
      realm: ${KEYCLOAK_REALM:bank-asia}
      admin-realm: ${KEYCLOAK_ADMIN_REALM:bank-asia}
      client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:iam-admin-service}
      client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:EsTcO7qo4tmbqrLBA4o96kFEdq7THT3c}

logging:
  level:
    org.springframework.security: INFO
    com.erainfotech.ums: INFO
